version: '2'

services:
  bank-multi-tenant1:
    image: bank-multi-tenant
    depends_on:
      - db
    ports:
      - "8080:8080"
  bank-multi-tenant2:
    image: bank-multi-tenant
    depends_on:
      - db
    ports:
      - "8081:8080"
  db:
    image: mysql:5.7.15
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank_multitenant
  rabbitmq:
    build: docker/rabbitmq/
